# Generated by Django 4.2.21 on 2025-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='address_line_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='billing_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='town',
            field=models.CharField(default='', max_length=25),
        ),
    ]
