# Generated by Django 4.2.21 on 2025-06-09 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_pizzaorder_address_line_1_pizzaorder_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PizzaOrders', to=settings.AUTH_USER_MODEL),
        ),
    ]
