# Generated by Django 4.2.21 on 2025-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_pizzaorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
