# Generated by Django 4.2.21 on 2025-05-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('dessert', models.ForeignKey(limit_choices_to={'active': 'Yes', 'category': 'Desserts'}, on_delete=django.db.models.deletion.CASCADE, related_name='dessert_deals', to='menu.extras')),
                ('drink', models.ForeignKey(limit_choices_to={'active': 'Yes', 'category': 'Drinks'}, on_delete=django.db.models.deletion.CASCADE, related_name='drink_deals', to='menu.extras')),
                ('pizza', models.ForeignKey(limit_choices_to={'active': 'Yes'}, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='menu.pizza')),
                ('side', models.ForeignKey(limit_choices_to={'active': 'Yes', 'category': 'Sides'}, on_delete=django.db.models.deletion.CASCADE, related_name='side_deals', to='menu.extras')),
            ],
            options={
                'verbose_name_plural': 'Combo Deals',
            },
        ),
    ]
